version: "3.9"
services:
  inventory-services-backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      labels:
        - inventory-services-backend
      args:
        - stage=${STAGE:-none}
    volumes:
        - ./inventory_services/app:/app
    entrypoint: "./entrypoint.sh"
    command: "dev"
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    depends_on:
      - redis-db

  payment-services-backend:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      labels:
        - payment-services-backend
      args:
        - stage=${STAGE:-none}
    volumes:
        - ./inventory_services/app:/app
    entrypoint: "./entrypoint.sh"
    command: "dev"
    ports:
      - ${PORT:-5002}:${PORT:-5002}
    depends_on:
      - redis-db

  redis-db:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "6379:6379"


volumes:
  redis_data:
