version: "3.9"
services:
  inventory-services-backend:
    restart: unless-stopped
    env_file:
      - ./inventory_services/.env
    build:
      context: ./inventory_services
      dockerfile: Dockerfile
      labels:
        - inventory-services-backend
      args:
        - stage=${STAGE:-none}
    volumes:
        - ./inventory_services/app:/inventory_services/app
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    depends_on:
      - redis-stack

  payment-services-backend:
    restart: unless-stopped
    env_file:
      - ./payment_services/.env
    build:
      context: ./payment_services
      dockerfile: Dockerfile
      labels:
        - payment-services-backend
      args:
        - stage=${STAGE:-none}
    volumes:
        - ./payment_services/app:/payment_services/app
    ports:
      - ${PORT:-5002}:${PORT:-5002}
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    volumes:
      - redis_stack_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  redis_stack_data:
